export const digifromaGraphQLMutations = {
	createCompany: `
    mutation createCompnay($company_input:CompanyInput!)
    {
        createCompany(companyInput:$company_input)
        {
            accountingNumber
            ape
            id
            name
            city
            cityCode
            code
            country
            countryCode
            email
            employeesCount
            externalId
            opcaNumber
            phone
            website
        }
    }
    `,
	updateCompany: `
    mutation updateCompnay($company_id:ID!,$company_input:CompanyInput!)
    {
        updateCompany(id:$company_id,companyInput:$company_input)
        {
            accountingNumber
            ape
            id
            name
            city
            cityCode
            code
            country
            countryCode
            email
            employeesCount
            externalId
            opcaNumber
            phone
            website
            contacts{
                id
                fax
                firstname
                lastname
                phone
                title
                email
                civility
                position
            }
        }
    }
    `,
	createInstructor: `
    mutation createInstructor($instructor_input:InstructorInput!)
    {
        createInstructor(instructorInput:$instructor_input)
        {
            academyId
            accountingNumber
            bio
            birthCity
            birthName
            birthRegion
            birthdate
            city
            cityCode
            civility
            code
            company
            contractAccepted
            cost
            country
            countryCode
            diploma
            dpcAdeli
            dpcRpps
            email
            externalId
            firstname
            id
            insertedAt
            instructorLegalNumber
            insurance
            lastname
            locale
            logo{
                id
                filename
            }
            nationality
            note
            phone
            profession
            roadAddress
            siret
            skills
            socialNumber
            status
            updatedAt
            vat
        }
    }`,
	updateInstructor: `
    mutation updateInstructor($instructor_id:ID!,$instructor_input:InstructorInput!)
    {
        updateInstructor(id:$instructor_id,instructorInput:$instructor_input)
        {
            academyId
            accountingNumber
            bio
            birthCity
            birthName
            birthRegion
            birthdate
            city
            cityCode
            civility
            code
            company
            contractAccepted
            cost
            country
            countryCode
            diploma
            dpcAdeli
            dpcRpps
            email
            externalId
            firstname
            id
            insertedAt
            instructorLegalNumber
            insurance
            lastname
            locale
            logo{
                id
                filename
            }
            nationality
            note
            phone
            profession
            roadAddress
            siret
            skills
            socialNumber
            status
            updatedAt
            vat
        }
    }`,
	createGrade: `
    mutation createGrade($grade_input:GradeInput!,$trainee_id:ID!,$training_session_id:ID!)
    {
        createGrade(gradeInput:$grade_input,traineeId:$trainee_id,trainingSessionId:$training_session_id)
        {
           id
           description
           label
           scoreComment
           scoreResult
           trainee{
            id
            firstname
            lastname
           }
           trainingSession{
            id
            name
           }
        }
    }`,
	updateGrade: `
    mutation updateGrade($grade_id:ID!,$grade_input:GradeInput!)
    {
        updateGrade(id:$grade_id,gradeInput:$grade_input)
        {
           id
           description
           label
           scoreComment
           scoreResult
           trainee{
            id
            firstname
            lastname
           }
           trainingSession{
            id
            name
           }
        }
    }`,
	createTrainee: `
    mutation createTrainee($trainee_input:TraineeInput!)
    {
        createTrainee(traineeInput:$trainee_input)
        {
            academyId
            accountingNumber
            birthCity
            birthCityCode
            birthName
            birthRegion
            birthdate
            city
            cityCode
            civility
            code
            company{
                id
                name
            }
            companyId
            companyName
            country
            countryCode
            dpcAdeli
            dpcMainStatus
            dpcRpps
            draft
            email
            externalId
            firstname
            freeText
            grades{
                id
                label
                scoreResult
            }
            handicaped
            hourlySalary
            id
            insertedAt
            isPartialUnemployment
            isSexualHarassmentVictim
            isTerrorismVictim
            lastDiploma
            lastname
            levelStudies
            locale
            logo{
                id
                filename
            }
            nationality
            note
            phone
            phoneSecondary
            position
            profession
            professionalCategory
            roadAddress
            siret
            socialCategory
            socialNumber
            status
            updatedAt
            vat
            vatAccountingCode
            workContractType
        }
    }`,
	updateTrainee: `
    mutation updateTrainee($trainee_id:ID!,$trainee_input:TraineeInput!)
    {
        updateTrainee(id:$trainee_id,traineeInput:$trainee_input)
        {
            academyId
            accountingNumber
            birthCity
            birthCityCode
            birthName
            birthRegion
            birthdate
            city
            cityCode
            civility
            code
            company{
                id
                name
            }
            companyId
            companyName
            country
            countryCode
            dpcAdeli
            dpcMainStatus
            dpcRpps
            draft
            email
            externalId
            firstname
            freeText
            grades{
                id
                label
                scoreResult
            }
            handicaped
            hourlySalary
            id
            insertedAt
            isPartialUnemployment
            isSexualHarassmentVictim
            isTerrorismVictim
            lastDiploma
            lastname
            levelStudies
            locale
            logo{
                id
                filename
            }
            nationality
            note
            phone
            phoneSecondary
            position
            profession
            professionalCategory
            roadAddress
            siret
            socialCategory
            socialNumber
            status
            updatedAt
            vat
            vatAccountingCode
            workContractType
        }
    }`,
	addInstructorToSlot: `
    mutation addInstructorToSlot($slot_id:ID!,$training_session_instructor_id:ID!)
    {
        addInstructorToSlot(slotId:$slot_id,trainingSessionInstructorId:$training_session_instructor_id)
        {
            id
            trainingSessionInstructor{
                id
                tutoringType
                days
                hours
                instructor{
                    id
                    firstname
                    lastname
                }
            }
            trainingSessionSlot{
                id
                slot
                startTime
                endTime
                date
            }

        }
    }`,
	removeInstructorFromSlot: `
    mutation removeInstructorFromSlot($slot_id:ID!,$training_session_instructor_id:ID!)
    {
        removeInstructorFromSlot(slotId:$slot_id,trainingSessionInstructorId:$training_session_instructor_id)
        {
            id
            trainingSessionInstructor{
                id
                tutoringType
                days
                hours
                instructor{
                    id
                    firstname
                    lastname
                }
            }
            trainingSessionSlot{
                id
                slot
                startTime
                endTime
                date
            }

        }
    }`,
	addInstructorToTrainingSession: `
    mutation addInstructorToTrainingSession
    (
        $contractAccepted:Boolean,
        $cost: Float,
        $costMode: InstructorCostMode,
        $days: Float,
        $hours: Float,
        $instructorId: ID!,
        $subcontractingBpf: Boolean,
        $trainingSessionId: ID!,
        $tutoringType: InstructorTutoringType,
        $vat: Float
    )
    {
        addInstructorToTrainingSession
        (
            contractAccepted:$contractAccepted,
            cost:$cost,
            costMode:$costMode,
            days:$days,
            hours:$hours,
            instructorId:$instructorId,
            subcontractingBpf:$subcontractingBpf,
            trainingSessionId:$trainingSessionId,
            tutoringType:$tutoringType,
            vat:$vat
        )
        {
            id
            contractAccepted
            cost
            costMode
            tutoringType
            days
            hours
            instructor{
                id
                firstname
                lastname
            }
            signatures{
                signature
            }
            subcontractingBpf
            trainingSession{
                id
                name
            }
            vat
            tutoringType
        }
    }`,
	removeInstructorFromTrainingSession: `
    mutation removeInstructorFromTrainingSession($training_session_instructor_id:ID!)
    {
        removeInstructorFromTrainingSession(trainingSessionInstructorId:$training_session_instructor_id)
        {
            id
            contractAccepted
            cost
            costMode
            tutoringType
            days
            hours
            instructor{
                id
                firstname
                lastname
            }
            signatures{
                signature
            }
            subcontractingBpf
            trainingSession{
                id
                name
            }
            vat
            tutoringType
        }
    }`,
	createQuotation: `
    mutation createQuotation($quotation_input:CreateQuotationInput!)
    {
        createQuotation(createQuotationInput:$quotation_input)
        {
            id
            date
            customer{
                id
            }
            items{
                id
                name
            }
            recipient{
                ...on Company{
                    id
                    name
                }
                ...on FundingAgency{
                    id
                    name
                }
                ...on Trainee{
                    id
                    firstname
                    lastname
                }
            }
            trainingSession{
                id
                name
            }

        }
    }`,
	updateQuotation: `
    mutation updateQuotation($quotation_id:ID!,$quotation_input:UpdateQuotationInput!)
    {
        updateQuotation(id:$quotation_id,updateQuotationInput:$quotation_input)
        {
            id
            date
            customer{
                id
            }
            items{
                id
                name
            }
            recipient{
                ...on Company{
                    id
                    name
                }
                ...on FundingAgency{
                    id
                    name
                }
                ...on Trainee{
                    id
                    firstname
                    lastname
                }
            }
            trainingSession{
                id
                name
            }

        }
    }`,
	createCustomer: `
    mutation createCustomer($customer_input:CreateCustomerInput!)
    {
        createCustomer(createCustomerInput:$customer_input)
        {
        id
           accountingNumber
           contracted
           contractedFundingUnknown
           crmStatus
           jobless
           stripeId
           vat
           foreignCustomer
           entity{
            ...on Trainee{
                id
                firstname
                lastname
            }
            ...on Company{
                id
                name
            }
           }
        }
    }`,
	updateCustomer: `
    mutation updateCustomer($customer_id:ID!,$customer_input:UpdateCustomerInput!)
    {
        updateCustomer(id:$customer_id,updateCustomerInput:$customer_input)
        {
            
           id
           accountingNumber
           contracted
           contractedFundingUnknown
           crmStatus
           jobless
           stripeId
           vat
           foreignCustomer
           entity{
            ...on Trainee{
                id
                firstname
                lastname
            }
            ...on Company{
                id
                name
            }
           }
        }
    }`,
	createTrainingSession: `
    mutation createTrainingSession($session_input:TrainingSessionInput!)
    {
        createTrainingSession(trainingSessionInput:$session_input)
        {
            averageDurationPerDate
            id
            name
            cityCode
            code
            codeFundae
            contracted
            diploma
            diplomaTitle
            manager {
              id
              firstname
              lastname
            }
            place
            placeName
            program {
              id
              name
            }
            qualityAnalysis
            qualityExpectations
            qualitySuccessConditions
            showDatesInExtranet
            showPlaceInExtranet
            showRulesInExtranet
            showTraineePedagogicalTrackingInExtranet
            showTraineesInExtranet
            specialty
            trainingType
            type
            useMap
            timezone
            vaeAdmissibilityDate
            
            academy {
              id
              contactEmail
            }
            address
            addressName
            attendanceId
            baseDocuments {
              id
              filename
            }
            cityCode
            comments {
              id
              author
              text
            }
            contracted
            costs {
              id
              cost
              costMode
              description
              type
              vat
            }
            customName
            customers {
              id
            }
            dates {
              date
              startTime
              endTime
              slot
            }
            datesGoogleUrl
            datesWebcalUrl
            dpc
            endDate
            
        }
    }`,
	updateTrainingSession: `
    mutation updateTrainingSession($session_id:ID!,$session_input:TrainingSessionInput!)
    {
        updateTrainingSession(id:$session_id,trainingSessionInput:$session_input)
        {
            averageDurationPerDate
            id
            name
            cityCode
            code
            codeFundae
            contracted
            diploma
            diplomaTitle
            manager {
            id
            firstname
            lastname
            }
            place
            placeName
            program {
            id
            name
            }
            qualityAnalysis
            qualityExpectations
            qualitySuccessConditions
            showDatesInExtranet
            showPlaceInExtranet
            showRulesInExtranet
            showTraineePedagogicalTrackingInExtranet
            showTraineesInExtranet
            specialty
            trainingType
            type
            useMap
            timezone
            vaeAdmissibilityDate
            
            academy {
            id
            contactEmail
            }
            address
            addressName
            attendanceId
            baseDocuments {
            id
            filename
            }
            cityCode
            comments {
            id
            author
            text
            }
            contracted
            costs {
            id
            cost
            costMode
            description
            type
            vat
            }
            customName
            customers {
            id
            }
            dates {
            date
            startTime
            endTime
            slot
            }
            datesGoogleUrl
            datesWebcalUrl
            dpc
            endDate
            
        }
    }`,
	deleteCustomer: `
    mutation deleteCustomer($customer_id:ID!){
        deleteCustomer(id:$customer_id)
        
    }`,
	createInvoice: `
    mutation createInvoice($invoice_input:CreateInvoiceInput!)
    {
        createInvoice(createInvoiceInput:$invoice_input)
        {
            accountingAnalytics
            id
            date
            freeText
            insertedAt
            items{
                id
                quantity
                name
                description
                vat
            }
            number
            prefix
            reference
            updatedAt
        }
    }`,
	updateInvoice: `
    mutation updateInvoice($invoice_id:ID!,$invoice_input:UpdateInvoiceInput!)
    {
        updateInvoice(id:$invoice_id,updateInvoiceInput:$invoice_input)
        {
            accountingAnalytics
            id
            date
            freeText
            insertedAt
            items{
                id
                quantity
                name
                description
                vat
            }
            number
            prefix
            reference
            updatedAt
        }
    }`,
	createInvoicePayment: `
    mutation createInvoicePayment($invoice_id:ID!,$payment_input:InvoicePaymentInput!)
    {
        createInvoicePayment(invoiceId:$invoice_id,invoicePaymentInput:$payment_input)
        {
            amount
            id
            date
            freeText
            stripeId
            mode
        }
    }`,
	updateInvoicePayment: `
    mutation updateInvoicePayment($payment_id:ID!,$payment_input:InvoicePaymentInput!)
    {
        updateInvoicePayment(id:$payment_id,invoicePaymentInput:$payment_input)
        {
            amount
            id
            date
            freeText
            stripeId
            mode
        }
    }`,
	createProgram: `
    mutation createProgram($program_input:ProgramInput!)
    {
        createProgram(programInput:$program_input)
        {
            accessDelay
            id
            name
            name
            accessDelayUnit
            accountingAnalytics
            rsCode
            rncpCode
            economicalModel
            
            durationInDays
            durationInHours
            version
            onSale
            certifInfoCode
            accountingNumber
            accountingNumberFundingAgency
            cpfCode
            admissionModality
            code
            category{
                id
                name
            }
            assessments{
                sourceId
                text
            }
            certificateurContratId
            certificateurId
            certificationDetails
            certificationIncludedInAdditionalExpenses
            certificationModalityAccess
            certificationModality
            certificationRegistrationDate
            certificationType
            certifiedData
            certifierName
            code
            cpf
            cpfCode
            createdAt
            description
            diploma
            diplomaName
            diplomaTitle
            documents{
                id
                filename
            }
            dpc
            durationInDays
            economicalModel
            enrollingLevelEnforced
            entryExitModality
            graduatedLevel
            graduationModality
            graduationTarget
            graduationValidityYears
            youtubeId
            version
            updatedAt
            transmitterCertificationId
            trainingType
            trainingPedagogicalModality
            trainingModality
            tailored
            subtitle
            rythm
            targets{
                sourceId
                text
            }
            steps{
                sourceId
                text
            }
            tags{
                name
            }
            trainingType
            targets{
                text
            }
            youtubeId
            pedagogicalResources{
                sourceId
                text
            }
            graduationTarget
            prerequisites{
                sourceId
                text
            }
            goals{
                sourceId
                text
            }
        }
    }`,
	updateProgram: `
    mutation updateProgram($program_id:ID!,$program_input:ProgramInput!)
    {
        updateProgram(id:$program_id,programInput:$program_input)
        {
            accessDelay
            id
            name
            name
            accessDelayUnit
            accountingAnalytics
            rsCode
            rncpCode
            economicalModel
            
            durationInDays
            durationInHours
            version
            onSale
            certifInfoCode
            accountingNumber
            accountingNumberFundingAgency
            cpfCode
            admissionModality
            code
            category{
                id
                name
            }
            assessments{
                sourceId
                text
            }
            certificateurContratId
            certificateurId
            certificationDetails
            certificationIncludedInAdditionalExpenses
            certificationModalityAccess
            certificationModality
            certificationRegistrationDate
            certificationType
            certifiedData
            certifierName
            code
            cpf
            cpfCode
            createdAt
            description
            diploma
            diplomaName
            diplomaTitle
            documents{
                id
                filename
            }
            dpc
            durationInDays
            economicalModel
            enrollingLevelEnforced
            entryExitModality
            graduatedLevel
            graduationModality
            graduationTarget
            graduationValidityYears
            youtubeId
            version
            updatedAt
            transmitterCertificationId
            trainingType
            trainingPedagogicalModality
            trainingModality
            tailored
            subtitle
            rythm
            targets{
                sourceId
                text
            }
            steps{
                sourceId
                text
            }
            tags{
                name
            }
            trainingType
            targets{
                text
            }
            youtubeId
            pedagogicalResources{
                sourceId
                text
            }
            graduationTarget
            prerequisites{
                sourceId
                text
            }
            goals{
                sourceId
                text
            }
        }
    }`,
	updateTrainingSubSession: `
    mutation updateSubsession($subsession_id:ID!,$subsession_input:SubsessionInput!)
    {
        updateSubsession(id:$subsession_id,subsessionInput:$subsession_input)
        {
            id
            name
            modality
            attendanceFromModules
            averageDurationPerDate
            datesAreInterval
            durationDays
            durationHours
            color
            costs{
                id
                type
                cost
                costMode
                costIndependant
                costIndividual
                vat
                description
                monthly
            }
        }
    }`,
	createTrainingSubSession: `
    mutation createSubsession($session_id:ID!,$subsession_input:SubsessionInput!){
        createSubsession(subsessionInput:$subsession_input,trainingSessionId:$session_id)
        {
            id
            name
            modality
            attendanceFromModules
            averageDurationPerDate
            datesAreInterval
            durationDays
            durationHours
            color
            costs{
                id
                type
                cost
                costMode
                costIndependant
                costIndividual
                vat
                description
                monthly
            }
        }
    }`,
	createAbandonWithSlots: `
    mutation createAbandonWithSlots($session_id:ID!,$trainee_id:ID!,$abandon_input:AbandonInput)
    {
        createAbandonWithSlots(trainingSessionId:$session_id,traineeId:$trainee_id,abandonInput:$abandon_input)
        {
            comment
            commentJustifiedAbsence
            id
            isAbandon
            isBack
            isJustified
            trainee
            {
                id
                firstname
                lastname
            }
            trainingSessionSlots
            {
                id
                endTime
                startTime
                slot
                bypassConflicts
                date
                insertedAt
                updatedAt
            }
        }
    }`,
    createCustomerTrainee:`
    mutation createCustomerTrainee($trainee_input:CreateCustomerTraineeInput!,$customer_id:ID!)
    {
        createCustomerTrainee(createCustomerTraineeInput:$trainee_input,customerId:$customer_id)
        {
                id
                signatures
                {
                    signature
                    type
                }
                extranetUrl
                assessment
                passed
                onWorkingTime
                sessionCompletion
                abandons
                {
                    comment
                    commentJustifiedAbsence
                    id
                    insertedAt
                    isAbandon
                    isBack
                    isJustified
                    updatedAt    
                }
                trainee
                {
                    academyId
                    accountingNumber
                    birthCity
                    birthCityCode
                    birthName
                    birthRegion
                    birthdate
                    city
                    cityCode
                    civility
                    code
                    company{
                        id
                        name
                    }
                    companyId
                    companyName
                    country
                    countryCode
                    dpcAdeli
                    dpcMainStatus
                    dpcRpps
                    draft
                    email
                    externalId
                    firstname
                    freeText
                    grades{
                        id
                        label
                        scoreResult
                    }
                    handicaped
                    hourlySalary
                    id
                    insertedAt
                    isPartialUnemployment
                    isSexualHarassmentVictim
                    isTerrorismVictim
                    lastDiploma
                    lastname
                    levelStudies
                    locale
                    logo{
                        id
                        filename
                    }
                    nationality
                    note
                    phone
                    phoneSecondary
                    position
                    profession
                    professionalCategory
                    roadAddress
                    siret
                    socialCategory
                    socialNumber
                    status
                    updatedAt
                    vat
                    vatAccountingCode
                    workContractType
                }

        }
    }`
};
