import { createAction, Property } from '@activepieces/pieces-framework';
import { digiformaAuth } from '../../..';
import { makeClient } from '../../common';
import { digiformaProps } from '../../common/props';

export const createProgramAction = createAction({
  auth: digiformaAuth,
  name: 'digiforma_create_program',
  displayName: 'Create Program',
  description: 'Creates a new program',
  props: {
    name: Property.ShortText({
      displayName: 'Name',
      required: true,
    }),
    ...digiformaProps.program,
  },
  async run(context) {
    const {
      name,
      subtitle,
      code,
      onSale,
      version,
      durationInDays,
      durationInHours,
      categoryId,
      description,
      accessDelay,
      accessDelayUnit,
      admissionModality,
      active,
      min,
      max,
      certificateurContratId,
      certificateurId,
      certificationModality,
      certificationModalityAccess,
      certificationType,
      certifiedData,
      certifierName,
      cpf,
      cpfCode,
      createdAt,
      enrollingLevel,
      enrollingLevelEnforced,
      graduatedLevel,
      entryExitModality,
      handicappedAccessibility,
      hoursCenter,
      hoursCompany,
      language,
      marketplaceCategoryId,
      marketplaceTargetLevel,
      sellOnMarketplace,
      showInstructors,
      trainingModality,
      youtubeId,
      transmitterCertificationId,
      trainingType,
      skillBlock,
      tailored,
      rncpCode,
      rsCode,
      rythm,
      accountingAnalytics,
      accountingNumber,
      accountingNumberFundingAgency,
      certifInfoCode,
      certificationDetails,
      certificationIncludedInAdditionalExpenses,
      certificationRegistrationDate,
      diploma,
      diplomaTitle,
      dpc,
      economicalModel,
      graduationTarget,
      graduationModality,
      graduationValidityYears,
      mentoring,
      satisfactionDescription,
      specialty,
      trainingPedagogicalModality,
    } = context.propsValue;

    const goals = context.propsValue.goals as string[];
    const targets = context.propsValue.targets as string[];
    const prerequisites = context.propsValue.prerequisites as string[];
    const assessments = context.propsValue.assessments as string[];
    const pedagogicalResources = context.propsValue.pedagogicalResources as string[];
    const steps = context.propsValue.steps as string[];
    const tags = context.propsValue.tags as string[];

    const client = makeClient(context.auth);
    return await client.createProgram({
      name,
      subtitle,
      code,
      onSale,
      version,
      durationInDays,
      durationInHours,
      categoryId,
      description,
      accountingAnalytics,
      accountingNumber,
      accountingNumberFundingAgency,
      certifInfoCode,
      certificationDetails,
      certificationIncludedInAdditionalExpenses,
      certificationRegistrationDate,
      diploma,
      diplomaTitle,
      dpc,
      economicalModel,
      graduationTarget,
      graduationModality,
      graduationValidityYears,
      mentoring,
      satisfactionDescription,
      specialty,
      trainingPedagogicalModality,
      goals: goals.map((text) => ({ text })),
      targets: targets.map((text) => ({ text })),
      prerequisites: prerequisites.map((text) => ({ text })),
      assessments: assessments.map((text) => ({ text })),
      accessDelay,
      accessDelayUnit,
      admissionModality,
      capacity: { active, min, max },
      certificateurContratId,
      certificateurId,
      certificationModality,
      certificationModalityAccess,
      certificationType,
      certifiedData,
      certifierName,
      cpf,
      cpfCode,
      createdAt,
      enrollingLevel,
      enrollingLevelEnforced,
      graduatedLevel,
      entryExitModality,
      handicappedAccessibility,
      hoursCenter,
      hoursCompany,
      language,
      marketplaceCategoryId,
      marketplaceTargetLevel,
      pedagogicalResources: pedagogicalResources.map((text) => ({ text })),
      sellOnMarketplace,
      showInstructors,
      trainingModality,
      youtubeId,
      transmitterCertificationId,
      steps: steps.map((text) => ({ text })),
      trainingType,
      skillBlock,
      tags,
      tailored,
      rncpCode,
      rsCode,
      rythm,
    });
  },
});
