import { createAction, Property } from '@activepieces/pieces-framework';
import { digiformaAuth } from '../../..';
import { digiformaCommon, makeClient } from '../../common';
import { digiformaProps } from '../../common/props';

export const updateTrainingSessionAction = createAction({
  auth: digiformaAuth,
  name: 'digiforma_update_training_session',
  displayName: 'Update Training Session',
  description: 'Updates an existing training session.',
  props: {
    trainingSessionId: digiformaCommon.trainingSessionId(true),
    name: Property.ShortText({
      displayName: 'Name',
      required: false,
    }),
    managerId: digiformaCommon.managerId(false, 'Administrator no.1', 'Administrator no.1'),
    secondManagerId: digiformaCommon.managerId(false, 'Administrator no.2', 'Administrator no.2'),
    programId: digiformaCommon.programId(false),
    ...digiformaProps.trainingSession,
  },
  async run(context) {
    const {
      trainingSessionId,
      name,
      code,
      cityCode,
      codeFundae,
      contracted,
      managerId,
      secondManagerId,
      programId,
      place,
      placeName,
      qualityAnalysis,
      qualityExpectations,
      qualitySuccessConditions,
      showDatesInExtranet,
      showPlaceInExtranet,
      showProgramInExtranet,
      showTraineePedagogicalTrackingInExtranet,
      showTraineesInExtranet,
      specialty,
      useMap,
      diploma,
      diplomaTitle,
      datesAreInterval,
      averageDurationPerDate,
      pipelineState,
      roomId,
      showRulesInExtranet,
      showSigningButtonInExtranet,
      dpc,
      inter,
      remote,
      timezone,
      trainingType,
      type,
      vaeAdmissibilityDate,
    } = context.propsValue;
    const client = makeClient(context.auth);
    return await client.updateTrainingSession(trainingSessionId!, {
      name,
      code,
      cityCode,
      codeFundae,
      contracted,
      managerId,
      secondManagerId,
      programId,
      place,
      placeName,
      qualityAnalysis,
      qualityExpectations,
      qualitySuccessConditions,
      showDatesInExtranet,
      showPlaceInExtranet,
      showProgramInExtranet,
      showTraineePedagogicalTrackingInExtranet,
      showTraineesInExtranet,
      specialty,
      useMap,
      diploma,
      diplomaTitle,
      datesAreInterval,
      averageDurationPerDate,
      pipelineState,
      roomId,
      showRulesInExtranet,
      showSigningButtonInExtranet,
      dpc,
      inter,
      remote,
      timezone,
      trainingType,
      type,
      vaeAdmissibilityDate,
    });
  },
});
